/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.View;

import edu.ijse.mvc.ItemDto.ItemDto;
import edu.ijse.mvc.ItemController.ItemController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pasan
 */
public class itemView extends javax.swing.JFrame {
    private ItemController itemController = new ItemController();
    /**
     * Creates new form itemView
     */
    public itemView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlItemCode = new javax.swing.JLabel();
        jtItemCode = new javax.swing.JTextField();
        jlDescription = new javax.swing.JLabel();
        jtDescription = new javax.swing.JTextField();
        jtPackSize = new javax.swing.JTextField();
        jlPackSi = new javax.swing.JLabel();
        jtUnitPrice = new javax.swing.JTextField();
        jlUnitPrice = new javax.swing.JLabel();
        jtQth = new javax.swing.JTextField();
        jlQth = new javax.swing.JLabel();
        jBDelete = new javax.swing.JButton();
        jBUpdate = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Item");

        jlItemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlItemCode.setText("ItemCode");

        jtItemCode.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jlDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlDescription.setText("Description");

        jtDescription.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jtPackSize.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jlPackSi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlPackSi.setText("Pack Size");

        jtUnitPrice.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jlUnitPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlUnitPrice.setText("Unit Price");

        jtQth.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jlQth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlQth.setText("Qty On Hand");

        jBDelete.setText("Delete");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBUpdate.setText("Update");
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });

        jBSave.setText("Save");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlUnitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPackSi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlItemCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jtPackSize, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtItemCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(140, 140, 140)
                        .addComponent(jlQth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(jtQth, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(416, 416, 416))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDelete)
                        .addGap(44, 44, 44)
                        .addComponent(jBUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(jBSave)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlItemCode)
                    .addComponent(jtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescription)
                    .addComponent(jtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPackSi)
                    .addComponent(jtPackSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUnitPrice)
                    .addComponent(jtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQth)
                    .addComponent(jtQth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDelete)
                    .addComponent(jBUpdate)
                    .addComponent(jBSave))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        saveItem();        // TODO add your handling code here:
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed
        updateItem();        // TODO add your handling code here:
    }//GEN-LAST:event_jBUpdateActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        deleteItem();        // TODO add your handling code here:
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        searchItem();        // TODO add your handling code here:
    }//GEN-LAST:event_tblItemMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlDescription;
    private javax.swing.JLabel jlItemCode;
    private javax.swing.JLabel jlPackSi;
    private javax.swing.JLabel jlQth;
    private javax.swing.JLabel jlUnitPrice;
    private javax.swing.JTextField jtDescription;
    private javax.swing.JTextField jtItemCode;
    private javax.swing.JTextField jtPackSize;
    private javax.swing.JTextField jtQth;
    private javax.swing.JTextField jtUnitPrice;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables

public void saveItem(){
    ItemDto itemDto = new ItemDto(jtItemCode.getText(),jtDescription.getText(),jtPackSize.getText(),Double.parseDouble(jtUnitPrice.getText()),Integer.parseInt(jtQth.getText()));
    System.out.println(itemDto);
    
    try {
        String resp = itemController.saveItem(itemDto);
        JOptionPane.showMessageDialog(this, resp);
        loadTable();
        clear();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    private void clear(){
        jtItemCode.setText("");
        jtDescription.setText("");
        jtPackSize.setText("");
        jtQth.setText("");
        jtUnitPrice.setText("");
    }

    private void loadTable(){
        String [] colums = {"ItemCode", "Description", "PackSize", "UnitPrice", "QtyOnHand"};
        DefaultTableModel dtm = new DefaultTableModel(colums, 0){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblItem.setModel(dtm);
        
        try {
            ArrayList<ItemDto> dtos = itemController.getAllItem();
            for(ItemDto dto : dtos){
                Object[] rowData = {dto.getId(),dto.getDesc(),dto.getPack(),dto.getUnitPrice(),dto.getQth()};
                dtm.addRow(rowData);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        private void searchItem(){
            String itemCode = (String) tblItem.getValueAt(tblItem.getSelectedRow(), 0);
            
            try {
                ItemDto itemDto = itemController.searchItem(itemCode);
                if (itemDto != null) {
                    jtItemCode.setText(itemDto.getId());
                    jtDescription.setText(itemDto.getDesc());
                    jtPackSize.setText(itemDto.getPack());
                    jtUnitPrice.setText(Double.toString(itemDto.getUnitPrice()));
                    jtQth.setText(Integer.toString(itemDto.getQth()));
                }
                else{
                    JOptionPane.showMessageDialog(this, "Item not Found");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        public void updateItem(){
        ItemDto itemDto = new ItemDto(jtItemCode.getText(), jtDescription.getText(),
                jtPackSize.getText(), Double.parseDouble(jtUnitPrice.getText()),
                Integer.parseInt(jtQth.getText()));
        
        System.out.println(itemDto);
        try {
            String resp = itemController.updateItem(itemDto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        public void deleteItem(){
        try {
            String resp = itemController.deleteItem(jtItemCode.getText());
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}


