/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.View;

import edu.ijse.mvc.ItemDto.CustomerDto;
import edu.ijse.mvc.ItemController.CustomerController;
import edu.ijse.mvc.ItemController.ItemController;
import edu.ijse.mvc.ItemController.OrderController;
import edu.ijse.mvc.ItemDto.OrderDetailDto;
import edu.ijse.mvc.ItemDto.ItemDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import edu.ijse.mvc.ItemDto.OrderDto;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author pasan
 */
public class OrderView extends javax.swing.JFrame {

    private CustomerController customerController = new CustomerController();
    private ItemController itemController = new ItemController();
    private OrderController orderController = new OrderController();
    private ArrayList<OrderDetailDto> orderDetailDtos = new ArrayList<>();
    /**
     * Creates new form OrderView
     */
    public OrderView() {
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlOrderId = new javax.swing.JLabel();
        jtOrderId = new javax.swing.JTextField();
        jlCusId = new javax.swing.JLabel();
        jTCusId = new javax.swing.JTextField();
        jbCusIdSearch = new javax.swing.JButton();
        jtItemCode = new javax.swing.JTextField();
        jbItemCodeSearch = new javax.swing.JButton();
        jlItemCode = new javax.swing.JLabel();
        jlqty = new javax.swing.JLabel();
        jtQty = new javax.swing.JTextField();
        jlDiscount = new javax.swing.JLabel();
        jtDiscount = new javax.swing.JTextField();
        jbAddToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCartTable = new javax.swing.JTable();
        jbPlaceOrder = new javax.swing.JButton();
        jlCusDetail = new javax.swing.JLabel();
        jlItemDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Details");

        jlOrderId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlOrderId.setText("Order Id");

        jtOrderId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlCusId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlCusId.setText("Customer Id");

        jTCusId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jbCusIdSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCusIdSearch.setText("Search");
        jbCusIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCusIdSearchActionPerformed(evt);
            }
        });

        jtItemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jbItemCodeSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbItemCodeSearch.setText("Search");
        jbItemCodeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbItemCodeSearchActionPerformed(evt);
            }
        });

        jlItemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlItemCode.setText("Item Code");

        jlqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlqty.setText("Qty");

        jtQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlDiscount.setText("Discount");

        jtDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jbAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAddToCart.setText("Add to Cart");
        jbAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddToCartActionPerformed(evt);
            }
        });

        jtCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCartTable);

        jbPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbPlaceOrder.setText("Place Order");
        jbPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlOrderId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCusId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTCusId, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jtOrderId))
                                .addGap(52, 52, 52)
                                .addComponent(jbCusIdSearch))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlqty, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jtItemCode))
                                .addGap(52, 52, 52)
                                .addComponent(jbItemCodeSearch)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlItemDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jlCusDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOrderId))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTCusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCusIdSearch)
                        .addComponent(jlCusDetail))
                    .addComponent(jlCusId))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbItemCodeSearch)
                        .addComponent(jlItemDetail))
                    .addComponent(jlItemCode))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlDiscount))
                    .addComponent(jtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlqty))
                .addGap(18, 18, 18)
                .addComponent(jbAddToCart)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbPlaceOrder)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbItemCodeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbItemCodeSearchActionPerformed
        searchItem();// TODO add your handling code here:
    }//GEN-LAST:event_jbItemCodeSearchActionPerformed

    private void jbAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddToCartActionPerformed
        addToCart();// TODO add your handling code here:
    }//GEN-LAST:event_jbAddToCartActionPerformed

    private void jbPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlaceOrderActionPerformed
        placeOrder();// TODO add your handling code here:
    }//GEN-LAST:event_jbPlaceOrderActionPerformed

    private void jbCusIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCusIdSearchActionPerformed
        searchCustomer();        // TODO add your handling code here:
    }//GEN-LAST:event_jbCusIdSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCusId;
    private javax.swing.JButton jbAddToCart;
    private javax.swing.JButton jbCusIdSearch;
    private javax.swing.JButton jbItemCodeSearch;
    private javax.swing.JButton jbPlaceOrder;
    private javax.swing.JLabel jlCusDetail;
    private javax.swing.JLabel jlCusId;
    private javax.swing.JLabel jlDiscount;
    private javax.swing.JLabel jlItemCode;
    private javax.swing.JLabel jlItemDetail;
    private javax.swing.JLabel jlOrderId;
    private javax.swing.JLabel jlqty;
    private javax.swing.JTable jtCartTable;
    private javax.swing.JTextField jtDiscount;
    private javax.swing.JTextField jtItemCode;
    private javax.swing.JTextField jtOrderId;
    private javax.swing.JTextField jtQty;
    // End of variables declaration//GEN-END:variables

    private void searchCustomer(){
        try{
            CustomerDto custDto = customerController.getCustomer(jTCusId.getText());
            if (custDto != null) {
                jlCusDetail.setText(custDto.getTitle()+" "+custDto.getName());
            }else{
                jlCusDetail.setText("Customer Not Found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void searchItem(){
        try {
            ItemDto itemDto = itemController.searchItem(jtItemCode.getText());
            if (itemDto != null) {
                jlItemDetail.setText(itemDto.getId()+" | "+itemDto.getDesc()+" | "+itemDto.getPack()+" | "+itemDto.getQth()+" | "+itemDto.getUnitPrice());
            }else{
                jlItemDetail.setText("Item Not Found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void initTable(){
        String[] columns = {"Item Code","Qty","Discount"};
        DefaultTableModel dtm = new DefaultTableModel(){
            public boolean isCellEditable(int row,int columns){
                return false;
            }
        };
        jtCartTable.setModel(dtm);
    }
    
    private void addToCart(){
        System.out.println("Add to card pressed");
        OrderDetailDto orderDetailDto = new OrderDetailDto();
        orderDetailDto.setDiscount(Integer.parseInt(jtDiscount.getText()));
        orderDetailDto.setQty(Integer.parseInt(jtQty.getText()));
        orderDetailDto.setItemCode(jtItemCode.getText());
        
        
        orderDetailDtos.add(orderDetailDto);
        
        Object[] rowData = {orderDetailDto.getItemCode(),orderDetailDto.getQty(),orderDetailDto.getDiscount()};
        DefaultTableModel dtm = (DefaultTableModel) jtCartTable.getModel();
        dtm.addRow(rowData);
    }
    
    private void placeOrder(){
        OrderDto orderDto = new OrderDto();
        orderDto.setCustId(jtOrderId.getText());
        orderDto.setOrderId(jtOrderId.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
        String dataString = sdf.format(new Date());
        orderDto.setDate(dataString);
        
        try {
            String resp = orderController.placeOrder(orderDto, orderDetailDtos);
            JOptionPane.showMessageDialog(this, resp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }   
}
